-- Central global de suporte. Reexecute mesmo se a primeira versao ja foi instalada.
begin;
alter table public.usuarios add column if not exists email text;
create table if not exists public.chamados_suporte (
  id_chamado bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id_empresa) on delete cascade,
  id_usuario bigint not null references public.usuarios(id_usuario), modulo text not null,
  prioridade text not null default 'NORMAL', assunto text not null, descricao text not null,
  status text not null default 'ABERTO', resposta text, criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
alter table public.chamados_suporte add column if not exists usuario_nome text;
alter table public.chamados_suporte add column if not exists usuario_email text;
alter table public.chamados_suporte add column if not exists empresa_nome text;
update public.chamados_suporte c set usuario_nome=coalesce(c.usuario_nome,u.nome),usuario_email=coalesce(c.usuario_email,u.email),empresa_nome=coalesce(c.empresa_nome,e.nome)
from public.usuarios u join public.empresas e on e.id_empresa=u.empresa_id where u.id_usuario=c.id_usuario;
create or replace function public.preencher_origem_chamado() returns trigger language plpgsql security definer set search_path=public,extensions as $$
declare u record; begin
  new.empresa_id:=public.app_empresa_atual(); new.id_usuario:=public.app_usuario_atual();
  select us.nome,us.email,e.nome empresa_nome into u from public.usuarios us join public.empresas e on e.id_empresa=us.empresa_id where us.id_usuario=new.id_usuario;
  new.usuario_nome:=u.nome; new.usuario_email:=u.email; new.empresa_nome:=u.empresa_nome; new.atualizado_em:=now(); return new;
end $$;
create index if not exists chamados_suporte_escopo_idx on public.chamados_suporte(empresa_id,id_usuario,criado_em desc);
alter table public.chamados_suporte enable row level security;
drop trigger if exists app_definir_escopo on public.chamados_suporte;
drop trigger if exists preencher_origem_chamado on public.chamados_suporte;
create trigger preencher_origem_chamado before insert on public.chamados_suporte for each row execute function public.preencher_origem_chamado();
do $$ declare p record; begin for p in select policyname from pg_policies where schemaname='public' and tablename='chamados_suporte' loop execute format('drop policy if exists %I on public.chamados_suporte',p.policyname); end loop; end $$;
create policy chamados_consultar on public.chamados_suporte for select to anon,authenticated using (id_usuario=public.app_usuario_atual() or public.verificar_superadmin_jr());
create policy chamados_criar on public.chamados_suporte for insert to anon,authenticated with check (id_usuario=public.app_usuario_atual() and empresa_id=public.app_empresa_atual());
create policy chamados_tratar on public.chamados_suporte for update to anon,authenticated using (public.verificar_superadmin_jr()) with check (public.verificar_superadmin_jr());
create or replace function public.app_criar_usuario(p_nome text,p_username text,p_senha text,p_ativo boolean,p_admin boolean,p_email text) returns jsonb language plpgsql security definer set search_path=public,extensions as $$
declare coluna_senha text; novo_id bigint; begin
  if not public.app_admin_atual() then raise exception 'Acesso negado'; end if;
  if exists(select 1 from public.usuarios where empresa_id=public.app_empresa_atual() and lower(username)=lower(trim(p_username))) then return jsonb_build_object('ok',false,'message','username ja existe'); end if;
  select column_name into coluna_senha from information_schema.columns where table_schema='public' and table_name='usuarios' and column_name in ('senha_hash','senha') order by case when column_name='senha_hash' then 0 else 1 end limit 1;
  execute format('insert into public.usuarios(nome,username,%I,ativo,admin,email,empresa_id) values($1,$2,$3,$4,$5,$6,$7) returning id_usuario',coluna_senha) into novo_id using trim(p_nome),trim(p_username),crypt(p_senha,gen_salt('bf')),p_ativo,p_admin,nullif(lower(trim(p_email)),''),public.app_empresa_atual();
  return jsonb_build_object('ok',true,'id_usuario',novo_id);
end $$;
grant execute on function public.app_criar_usuario(text,text,text,boolean,boolean,text) to anon,authenticated;
commit;
select u.nome,u.email from public.usuarios u join public.empresas e on e.id_empresa=u.empresa_id where lower(e.codigo)='jr' and u.admin and u.ativo and nullif(trim(u.email),'') is not null;
