-- Central de chamados, isolada por empresa e usuario.
create table if not exists public.chamados_suporte (
  id_chamado bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id_empresa) on delete cascade,
  id_usuario bigint not null references public.usuarios(id_usuario),
  modulo text not null,
  prioridade text not null default 'NORMAL' check (prioridade in ('BAIXA','NORMAL','ALTA','URGENTE')),
  assunto text not null,
  descricao text not null,
  status text not null default 'ABERTO' check (status in ('ABERTO','EM_ATENDIMENTO','AGUARDANDO_USUARIO','RESOLVIDO','CANCELADO')),
  resposta text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists chamados_suporte_escopo_idx
  on public.chamados_suporte(empresa_id,id_usuario,criado_em desc);

alter table public.chamados_suporte enable row level security;
drop trigger if exists app_definir_escopo on public.chamados_suporte;
create trigger app_definir_escopo before insert on public.chamados_suporte
for each row execute function public.app_escopo_usuario_insert();

drop policy if exists chamados_suporte_escopo on public.chamados_suporte;
create policy chamados_suporte_escopo on public.chamados_suporte
for all to anon,authenticated
using (public.app_pode_acessar_registro(empresa_id,id_usuario))
with check (public.app_pode_acessar_registro(empresa_id,id_usuario));
